### PR TITLE
DEV-837: update csv upload samples with newest functionality

### PR DESCRIPTION
**Pull request by BoHuang2018**
This change is [Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)

### CODE REVIEW

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: all files reviewed, 2 unresolved discussions (waiting on @BoHuang2018)

___
*[`scripts/ps1/upload_data.ps1` line 54 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGBjht67iEKFfw6et9:-NGGBjht67iEKFfw6etA:bvnyo86) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/ps1/upload_data.ps1#L54)):*
> ```PowerShell
>     --pit-current-time
> 
> Pop-Location
> ```

Should this be at end of file (i.e. below additional examples below)?
___
*[`scripts/sh/upload_data.sh` line 73 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGC0w736ITY6xaYRBx:-NGGC0w736ITY6xaYRBy:br2anz2) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/sh/upload_data.sh#L73)):*
> ```Shell
> #python -m exabel_data_sdk.scripts.load_time_series_from_file \
> #    --filename="./resources/data/time_series/brand_time_series_one_day.csv" \
> #    --pit-current-time
> ```

Missing newline at end of file

**Review by BoHuang2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @oyvindwe)

___
*[`scripts/ps1/upload_data.ps1` line 54 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGBjht67iEKFfw6et9:-NGGPDHh6eIY_VnwA_vC:bjvqjp4) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/ps1/upload_data.ps1#L54)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

Should this be at end of file (i.e. below additional examples below)?
</blockquote></details>

My first time to use powershell commands. 
Searched out some learning materials. 
I think you are right.  The `Pop-Location` should be at end of file. Because the it will retrieve the stored output.
Done.
___
*[`scripts/sh/upload_data.sh` line 73 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGC0w736ITY6xaYRBx:-NGGPnMKADdCvbh_v3Gn:b-f2oljv) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/sh/upload_data.sh#L73)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

Missing newline at end of file
</blockquote></details>

Nice catch.
Done

**Review by oyvindwe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: all files reviewed, 1 unresolved discussion (waiting on @BoHuang2018)

___
*[`scripts/sh/upload_data.sh` line 73 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGC0w736ITY6xaYRBx:-NGGeqXgCQ-Ht_tEVk36:b-jcqhq) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/sh/upload_data.sh#L73)):*
<details><summary><i>Previously, BoHuang2018 (BoHuang) wrote…</i></summary><blockquote>

Nice catch.
Done 
</blockquote></details>

It's still missing. Check your editor settings?

**Review by aksestok — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @BoHuang2018)

___
*[`scripts/ps1/upload_data.ps1` line 54 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGBjht67iEKFfw6et9:-NGGhi4I20l_hf5sAzEK:b-v05isc) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/ps1/upload_data.ps1#L54)):*
<details><summary><i>Previously, BoHuang2018 (BoHuang) wrote…</i></summary><blockquote>

My first time to use powershell commands. 
Searched out some learning materials. 
I think you are right.  The `Pop-Location` should be at end of file. Because the it will retrieve the stored output.
Done.
</blockquote></details>

It should be moved to the bottom of the file, yes. The `Pop-Location` has nothing to do with retrieving output. It [changes directory back](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/pop-location?view=powershell-7.2) to where the script was run from :blush: 
___
*[`scripts/sh/upload_data.sh` line 21 at r2](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGixsz1ue9aCNjaN6p:-NGGixsz1ue9aCNjaN6q:b-edyuan) ([raw file](https://github.com/exabel/csv-upload-sample/blob/47be790a4656e6209a4af40a7d6693705fdc9611/scripts/sh/upload_data.sh#L21)):*
> ```Shell
>     --api-key="$EXABEL_API_KEY" \
> 		--name="entityTypes/$EXABEL_NAMESPACE.brand" --display-name="brand" \
> 		--no-is-associative
> ```

Should be replaced with spaces for consistency.



_Suggestion:_
```Shell
    --name="entityTypes/$EXABEL_NAMESPACE.brand" --display-name="brand" \
    --no-is-associative
```
___
*[`scripts/sh/upload_data.sh` line 33 at r2](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGj7uwC6zwnD4xy-8v:-NGGj7uwC6zwnD4xy-8w:b2nreh6) ([raw file](https://github.com/exabel/csv-upload-sample/blob/47be790a4656e6209a4af40a7d6693705fdc9611/scripts/sh/upload_data.sh#L33)):*
> ```Shell
> python -m exabel_data_sdk.scripts.create_relationship_type \
> 		--name="relationshipTypes/$EXABEL_NAMESPACE.HAS_BRAND" \
> 		--is-ownership
> ```

Same as above.



_Suggestion:_
```Shell
    --name="relationshipTypes/$EXABEL_NAMESPACE.HAS_BRAND" \
    --is-ownership
```

**Review by aksestok — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @BoHuang2018)

**Review by BoHuang2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @aksestok and @oyvindwe)

___
*[`scripts/ps1/upload_data.ps1` line 54 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGBjht67iEKFfw6et9:-NGGkVb30xIGdESkm760:bu8zz6l) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/ps1/upload_data.ps1#L54)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

It should be moved to the bottom of the file, yes. The `Pop-Location` has nothing to do with retrieving output. It [changes directory back](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/pop-location?view=powershell-7.2) to where the script was run from :blush: 
</blockquote></details>

It does retrieve the stored output. `Retrieving the stored output` contains `Changing directory back to where the script was run from`.
There is some logic in it 😊😊😊
___
*[`scripts/sh/upload_data.sh` line 73 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGC0w736ITY6xaYRBx:-NGGit2c2jEoakaCtddi:bjs9kae) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/sh/upload_data.sh#L73)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

It's still missing. Check your editor settings?
</blockquote></details>

Oh, Sorry.  I was staring at the `.ps1` file.   This one is the `.sh` file. 
The new line was added. 
New empty line is not visible on Github's UI. I doubled checked with two different IDEs locally. It exists. 
Hope it is fixed. 
___
*[`scripts/sh/upload_data.sh` line 21 at r2](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGixsz1ue9aCNjaN6p:-NGGmInS7oKA5d7ItVue:b5bvr6x) ([raw file](https://github.com/exabel/csv-upload-sample/blob/47be790a4656e6209a4af40a7d6693705fdc9611/scripts/sh/upload_data.sh#L21)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Should be replaced with spaces for consistency.
</blockquote></details>

It should not be two spaces, but four spaces 😊😊😊
Done.
___
*[`scripts/sh/upload_data.sh` line 33 at r2](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGj7uwC6zwnD4xy-8v:-NGGmON4B8Q9x32sApc0:b-3lrv17) ([raw file](https://github.com/exabel/csv-upload-sample/blob/47be790a4656e6209a4af40a7d6693705fdc9611/scripts/sh/upload_data.sh#L33)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Save as above.
It should not be two spaces, but four spaces 😊😊😊
Done.

**Review by oyvindwe — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: all files reviewed, 3 unresolved discussions (waiting on @aksestok)

___
*[`scripts/sh/upload_data.sh` line 73 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGC0w736ITY6xaYRBx:-NGGqlzv6MR9sc-7D5eu:b423fa9) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/sh/upload_data.sh#L73)):*
<details><summary><i>Previously, BoHuang2018 (BoHuang) wrote…</i></summary><blockquote>

Oh, Sorry.  I was staring at the `.ps1` file.   This one is the `.sh` file. 
The new line was added. 
New empty line is not visible on Github's UI. I doubled checked with two different IDEs locally. It exists. 
Hope it is fixed. 
</blockquote></details>

Yes, it's correct now.

**Review by aksestok — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: all files reviewed, 1 unresolved discussion (waiting on @BoHuang2018)

*[a discussion](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGth2T0NI6Xfy1SZPU:-NGGth2T0NI6Xfy1SZPV:b-u2fp24) (no related file):*
In order for the changes to be runnable for a user, you need to update the `exabel-data-sdk` to at least [version 3.3.0](https://github.com/Exabel/python-sdk/releases/tag/v3.3.0), but preferably all the way to the [latest version](https://github.com/Exabel/python-sdk/releases/latest). See the [pipenv documentation](https://pipenv.pypa.io/en/latest/basics/#example-pipenv-upgrade-workflow) for how to update packages.

___
___
*[`scripts/sh/upload_data.sh` line 21 at r2](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGixsz1ue9aCNjaN6p:-NGGt2Eo3hsrLUljjjX-:bv6ame1) ([raw file](https://github.com/exabel/csv-upload-sample/blob/47be790a4656e6209a4af40a7d6693705fdc9611/scripts/sh/upload_data.sh#L21)):*
<details><summary><i>Previously, BoHuang2018 (BoHuang) wrote…</i></summary><blockquote>

It should not be two spaces, but four spaces 😊😊😊
Done.
</blockquote></details>

Yes, exactly like the suggested edit.

**Review by BoHuang2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @aksestok)

*[a discussion](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGth2T0NI6Xfy1SZPU:-NGGxxWE-na8Lx9YL9Rj:b-arn2jp) (no related file):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

In order for the changes to be runnable for a user, you need to update the `exabel-data-sdk` to at least [version 3.3.0](https://github.com/Exabel/python-sdk/releases/tag/v3.3.0), but preferably all the way to the [latest version](https://github.com/Exabel/python-sdk/releases/latest). See the [pipenv documentation](https://pipenv.pypa.io/en/latest/basics/#example-pipenv-upgrade-workflow) for how to update packages.
</blockquote></details>

The pipenv documentation link has nothing to do with helping a user to run the changed samples. 
I kindly suggested that we add a session about updating in the `README.md` file. 
The session has been added. Could you please have a look ? 😊😊😊

___
___
*[`scripts/sh/upload_data.sh` line 73 at r1](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGC0w736ITY6xaYRBx:-NGH3z6KEcCMS26qs5pc:bdrshck) ([raw file](https://github.com/exabel/csv-upload-sample/blob/f7242dc1e3d1e94de9442c1a198b44b13218b311/scripts/sh/upload_data.sh#L73)):*
<details><summary><i>Previously, oyvindwe (Øyvind Matheson Wergeland) wrote…</i></summary><blockquote>

Yes, it's correct now.
</blockquote></details>

Thanks for the confirming.
___
*[`scripts/sh/upload_data.sh` line 21 at r2](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGixsz1ue9aCNjaN6p:-NGGwdmmAvteb3_bbZAD:b-k6zclu) ([raw file](https://github.com/exabel/csv-upload-sample/blob/47be790a4656e6209a4af40a7d6693705fdc9611/scripts/sh/upload_data.sh#L21)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Yes, exactly like the suggested edit.
</blockquote></details>

The suggested edit looked like two spaces. Interesting 😊😊😊

**Review by aksestok — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: all files reviewed, 3 unresolved discussions (waiting on @BoHuang2018)

*[a discussion](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGth2T0NI6Xfy1SZPU:-NGH4jX56c7m_NAyXG6I:b8x68uh) (no related file):*
<details><summary><i>Previously, BoHuang2018 (BoHuang) wrote…</i></summary><blockquote>

The pipenv documentation link has nothing to do with helping a user to run the changed samples. 
I kindly suggested that we add a session about updating in the `README.md` file. 
The session has been added. Could you please have a look ? 😊😊😊
</blockquote></details>

Sorry if I was unclear, my suggestion was for you to update the dependencies in the repository. We have bundled a `Pipfile` and `Pipfile.lock` in the repository that makes it possible for users to get the exact same package versions that we have verified works.

If the users run `pipenv sync` with the current `Pipfile.lock` they will end up with version `2.0.0` of the SDK which does not include the methods or scripts to create entity types.

___
___
*[`README.md` line 16 at r5](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGH5CKJ7hMLagS86X2t:-NGH5CKJ7hMLagS86X2u:b-wsgoj2) ([raw file](https://github.com/exabel/csv-upload-sample/blob/a66d835695963b5da3bf88ecb96d4e9ad3a13dd9/README.md#L16)):*
> ```Markdown
> Exabel data model
> 
> ## Installation 
> ```

Unintentional edit (trailing hyphen) should be removed.



_Suggestion:_
```Markdown
## Installation
```
___
*[`README.md` line 35 at r5](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGH5G_K4QA-hx5P1Zri:-NGH5G_K4QA-hx5P1Zrj:brs1drh) ([raw file](https://github.com/exabel/csv-upload-sample/blob/a66d835695963b5da3bf88ecb96d4e9ad3a13dd9/README.md#L35)):*
> ```Markdown
> pipenv update exabel-data-sdk
> ```
> ```

I don't think this section adds any value. The point of the bundled `Pipfile` and `Pipfile.lock` is for the user to get a consistent virtual environment with package versions we know work with the code in the repository.

**Review by aksestok — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: all files reviewed, 3 unresolved discussions (waiting on @BoHuang2018)

*[a discussion](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGth2T0NI6Xfy1SZPU:-NGHDLkE7yKsrNLnkzAA:b-bezwf0) (no related file):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Sorry if I was unclear, my suggestion was for you to update the dependencies in the repository. We have bundled a `Pipfile` and `Pipfile.lock` in the repository that makes it possible for users to get the exact same package versions that we have verified works.

If the users run `pipenv sync` with the current `Pipfile.lock` they will end up with version `2.0.0` of the SDK which does not include the methods or scripts to create entity types.
</blockquote></details>

Just run `pipenv update` and push the resulting `Pipfile.lock`.

___

**Review by BoHuang2018 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4)* status: Pipfile.lock ignored, 3 of 4 files reviewed, 3 unresolved discussions (waiting on @aksestok)

*[a discussion](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGGth2T0NI6Xfy1SZPU:-NGH73zi1F4V-CvcVs7X:b-hpk79r) (no related file):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Just run `pipenv update` and push the resulting `Pipfile.lock`.
</blockquote></details>

Oh, no need to say sorry Aksel.  We all need to improve the communication. 
Yes, updating `Pipfile.lock` is a solution.  

I tried the `pipenv update`. It brings much changing to `Pipfile.lock`, many new sessions.
Since all the changes look like necessary, let's try it. 

___
___
*[`README.md` line 16 at r5](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGH5CKJ7hMLagS86X2t:-NGHIBdp1GjxJqjYnLw7:bxsxao0) ([raw file](https://github.com/exabel/csv-upload-sample/blob/a66d835695963b5da3bf88ecb96d4e9ad3a13dd9/README.md#L16)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

Unintentional edit (trailing hyphen) should be removed.
</blockquote></details>

The commit on `README.md` has been reverted.
___
*[`README.md` line 35 at r5](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-NGH5G_K4QA-hx5P1Zri:-NGHHi_E4v2mjFXREHTb:bd1209j) ([raw file](https://github.com/exabel/csv-upload-sample/blob/a66d835695963b5da3bf88ecb96d4e9ad3a13dd9/README.md#L35)):*
<details><summary><i>Previously, aksestok (Aksel Stokseth) wrote…</i></summary><blockquote>

I don't think this section adds any value. The point of the bundled `Pipfile` and `Pipfile.lock` is for the user to get a consistent virtual environment with package versions we know work with the code in the repository.
</blockquote></details>

Remove. We take the `pipenv update` strategy.

**Review by aksestok — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/exabel/csv-upload-sample/4#-:-NGHM2K3EqpIZPEo1Wys:bnfp4nl)* status: :shipit: complete! Pipfile.lock ignored, all files reviewed, all discussions resolved

**Pull request merged**
